### ISSUE TITLE
Migrate to FAKE 5

### ISSUE THREAD

**Issue by tangentsoft** [ionide/Forge#117]
I'm a new user of Forge, so maybe I'm missing something, but it appears that Forge only generates projects for the old version of FAKE. They've apparently [broken everything](https://fake.build/fake-migrate-to-fake-5.html) in FAKE 5. 

## Steps to Reproduce (for bugs)
1. Install ionide-* into VSCode, Cmd-Shift-P -> F# New Project -> answer questions.
2. F5, set up build task.
3. Observe complaint about "This runner is now obsolete with FAKE 5..." in VSCode Output panel.

## Your Environment
Up-to-date VSCode, dotnet 2.1.3, FAKE 5 installed both via Forge (?) and separately via `dotnet tool install fake-cli -g`.

**Comment by matthid** [comment]
> broken everything

is probably a but harsh for something that still works and generates a warning only ;)

**Comment by Krzysztof-Cieslak** [comment]
Done as part of 3.0 update (https://github.com/ionide/Forge/pull/120)
