### ISSUE TITLE
"forge add project --help" Shows parameter information for adding references

### ISSUE THREAD

**Issue by willnationsdev** [ionide/Forge#125]
**Describe the bug**
When executing `forge add project --help`, the output is as follows (having just installed forge from scoop):

    project : Adds project reference to project
    Available parameters:
    USAGE: forge.exe [--help] [--name <string>] [--project <string>]
    
    OPTIONS:
    
    --name, -n <string>   Project reference path
    --project, -p <string>
                          Project to which reference will be added
    --help                display this list of options.

You can see the all information details how one adds a reference to a project and not a project to a solution (or what to call the project, what type of project it should be, etc.).

**To Reproduce**
Execute `forge add project --help`

**Expected behaviour**
Parameters and descriptions should reflect how one can customize a project's creation in a solution. Expected output folder, project name (clearly denoting whether a subdirectory is made for the project inside the output folder, or if it is just placed directly in the output folder), customization of what sort of project we are creating (ClassLib, console app, web app, some other template installed via `dotnet new` under-the-hood, etc.). I'm not sure what all features are available in Forge yet since I just learned about it recently.

**Screenshots**
N/A

**Environment:**
 - OS: Windows 10
 - Visual Studio version: 2017
 - dotnet SDK version: 2.2.106
 - mono / .Net Framework version: wanted to create a net452 project adjacent to two netcoreapp2.2 projects.

**Additional context**
N/A

**Comment by willnationsdev** [comment]
Looks like the AddProjectArgs type outlines the help information and values and the `addProject` function contains the implementation. Not sure what the `<@ @>` operators are doing, nor where the Furnace module / load method combo is defined. Wouldn't mind taking a crack at fixing this myself if I had an idea of how those things worked (I'm quite new to the whole .NET ecosystem, but this doesn't seem terribly difficult, on the surface of it).

**Comment by Krzysztof-Cieslak** [comment]
Given all the changes in the ecosystem, Forge will be just utility for moving/adding files. Adding projects can be done with `dotnet add reference`
