### ISSUE TITLE
(On Windows) Surround `Forge` command path with quotes against path with spaces

### ISSUE THREAD

**Issue by OmanF** [ionide/Forge#126]
**Is your feature request related to a problem? Please describe.**
When the *full* path to the `Forge` application contains spaces (more common on Windows, though I guess could well be on macOS/Linux), the command fails with a "No executable found matching command {{partial path up to the first space character}}"

**Describe the solution you'd like**
I think the easiest solution would be to surround the full path to the `Forge` application in quotes.

**Describe alternatives you've considered**
Another idea, more involved, is to parse the full path and somehow (how?) deal with the spaces while not disturbing the user's file structure's ordering...

**Additional context**
By the way, regardless of the end results, the toast "Project was created" **always** shows up, which is misleading, confusing and (a little) irritating when, in fact, no project was created.
As an aside, I'd say, wait (and/or validate against the file system itself) for the project creation to *actually* be over before toasting (and, on error, toast an error message).

![broken_path](https://user-images.githubusercontent.com/7848797/61375715-db0f7300-a89f-11e9-86dd-5a4ab2b95778.png)

**Comment by josefblaha** [comment]
This issue should be moved to ionide-vscode-fsharp repository. It's not a problem on the callee side (Forge CLI), but on the caller side (the VS Code plugin).

@Krzysztof-Cieslak, can you move it?
