### ISSUE TITLE
New Project Template for AWS Lambda

### ISSUE THREAD

**Issue by mario-campos** [ionide/Forge#21]
## Expected Behavior

It should be simple to create a new project based on the template defined in the blog post [F# on AWS Lambda](http://lukemerrett.com/fsharp-on-aws-lambda/). TL;DR The actual template is on [Luke's Github](https://github.com/lukemerrett/FSharp-Template-for-Aws-Lambda).

## Current Behavior
Without an AWS Lambda project template, one has to `git clone` [Luke's template](https://github.com/lukemerrett/FSharp-Template-for-Aws-Lambda) first, and then modify it as necessary.

## Possible Solution
It doesn't seem to be too difficult to do? It looks like it's mainly a minimum of three files:

- *project.json*
- *nuget.config*
- some initial code file

## Context
I use AWS and I'm looking to expand my use of AWS to all of its available services, including AWS Lambda for quickly deploying API-backed scripts. AWS Lambda supports a few languages (NodeJS, Python, Java, C#/.NET Core), but I would *really* like to use F#. Thanks to Luke, he has shown it's possible—and I've confirmed through my own testing. I would simply like to make this use-case easy and accessible for others, as well as myself.

## Your Environment
- Windows 7
- Ionide / VS Code
- .NET Core 1.0.1

**Comment by Krzysztof-Cieslak** [comment]
Forge 3.0 will use `dotnet new` templates
