### ISSUE TITLE
does forge list files need the --solution parameter?

### ISSUE THREAD

**Issue by selketjah** [ionide/Forge#29]
According to the help, you should be able to list the files of a solution:

![image](https://cloud.githubusercontent.com/assets/2250570/21427187/43a1920c-c853-11e6-9f3c-b49fc57c4013.png)

But in the code, this parameter is not used:
![image](https://cloud.githubusercontent.com/assets/2250570/21427249/c07b19a6-c853-11e6-9cda-18f5ecec902b.png)

So either the parameter should be removed from the help or it needs to be implemented.

**Comment by Krzysztof-Cieslak** [comment]
`--solution` parameter should be implemented I guess. The plan was to make it list files added directly in solution file.

Also it should be XOR with `project` parameter.

**Comment by Krzysztof-Cieslak** [comment]
Given all the changes in the ecosystem, Forge will be just utility for moving/adding files
