### ISSUE TITLE
Implement list projects command

### ISSUE THREAD

**Issue by selketjah** [ionide/Forge#30]
Implement 'forge list projects'

 projects : List projects in solution
 Available parameters:

        --solution [-s] <string>: List the projects in this solution
        --folder [dir|--dir] <string>: List the projects in this directory
        --filter <string>: Filter list via fuzzy search for this string

**Comment by Phrohdoh** [comment]
What would be the point of `--folder <string>` when you could just `ls .*proj`?

**Comment by Krzysztof-Cieslak** [comment]
Given all the changes in the ecosyste
