### ISSUE TITLE
Wishlist: add Fake support to existing project

### ISSUE THREAD

**Issue by vivainio** [ionide/Forge#43]
Many F# projects (created with VS new project wizard) could be supported by a pretty simple Fake build tasks.

Add a new command ("forge add fake" or whatever) that would create build.fsx, build.cmd and build.sh along with some basic tasks (run msbuild, deploy zip) after looking around for .sln file.

**Comment by Krzysztof-Cieslak** [comment]
Given all the changes in the ecosystem, Forge will be just utility for moving/adding files
