### ISSUE TITLE
Idea/Enhancement: Show a list of projects for commands where one is required but not supplied

### ISSUE THREAD

**Issue by kragt** [ionide/Forge#98]
I've (partly, no solution support) implemented the command to list projects, and I got to thinking that maybe Forge could show a list of available projects (like the template list when making a new project) for the commands where a project is required but the supplied in the arguments.

Example: `forge.exe list files` would then list the available projects and wait for a selection instead of doing nothing.

I haven't used Forge enough for "real world" work yet to know if it would bring enough value to make it worth having or if it is preferable in a general workflow to have Forge do nothing if the project argument is missing.

(Also after my brain woke up again I realized this was a better place to discuss it than on slack.)

**Comment by Krzysztof-Cieslak** [comment]
I'm not really sure what is "real world" Forge usage - I've been using it mostly as utility for Ionide's project management, and in this part I don't use any "interactive" commands.

**Comment by kragt** [comment]
This is very out-of-date now (I just stumbled back past it) and not really in any kind useful with how Forge is used presently, so I'll close this again.
